import os
import torch
import torch.nn as nn
from typing import Optional

from models.actor_critic import ActorCriticPPO, ActorNetwork


class PolicyExporter:
    def __init__(self, policy: ActorCriticPPO, state_dim: int = 14, action_dim: int = 4):
        self.policy = policy
        self.actor = policy.actor
        self.state_dim = state_dim
        self.action_dim = action_dim

    def export_onnx(self, output_path: str = "./export_models/policy.onnx") -> str:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        self.actor.eval()
        
        class ActorMeanWrapper(nn.Module):
            def __init__(self, actor_net: ActorNetwork):
                super().__init__()
                self.actor_net = actor_net
                
            def forward(self, state: torch.Tensor) -> torch.Tensor:
                mu, _ = self.actor_net(state)
                return mu
                
        wrapper = ActorMeanWrapper(self.actor)
        wrapper.eval()
        dummy_input = torch.zeros(1, self.state_dim, dtype=torch.float32)
        
        try:
            torch.onnx.export(
                wrapper,
                dummy_input,
                output_path,
                export_params=True,
                opset_version=18,
                do_constant_folding=True,
                input_names=["observation"],
                output_names=["action_torque"],
                dynamic_axes={"observation": {0: "batch_size"}, "action_torque": {0: "batch_size"}},
            )
        except (ImportError, ModuleNotFoundError) as error:
            raise RuntimeError("ONNX export requires the 'onnx' and 'onnxscript' packages.") from error
        return output_path

    def export_cpp_header(self, output_path: str = "./export_models/embedded_policy.h") -> str:
        """Write a compact header containing the actor's affine layers.

        The generated header is dependency-free and mirrors Linear, LayerNorm,
        and Tanh layers in the actor mean network.
        """
        layers = list(self.actor.backbone) + [self.actor.mu_layer]
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        def floats(values: torch.Tensor) -> str:
            return ", ".join(f"{value:.9g}f" for value in values.detach().cpu().reshape(-1).tolist())

        lines = ["#pragma once", "#include <cmath>", "", "// Generated by PolicyExporter."]
        lines.append(f"constexpr int kObservationSize = {self.state_dim};")
        lines.append(f"constexpr int kActionSize = {self.action_dim};")
        lines.append("inline float tanh_activation(float x) { return std::tanh(x); }")
        lines.append("inline void compute_robot_action(const float observation[kObservationSize], float action[kActionSize]) {")
        previous_name = "observation"
        tensor_index = 0
        for index, layer in enumerate(layers):
            if isinstance(layer, nn.Linear):
                output_size, input_size = layer.weight.shape
                weight_name, bias_name, output_name = f"w{index}", f"b{index}", f"x{tensor_index}"
                tensor_index += 1
                is_output = index == len(layers) - 1
                lines.append(f"  static const float {weight_name}[{output_size * input_size}] = {{{floats(layer.weight)}}};")
                lines.append(f"  static const float {bias_name}[{output_size}] = {{{floats(layer.bias)}}};")
                lines.append(f"  float {output_name}[{output_size}];")
                lines.append(f"  for (int i = 0; i < {output_size}; ++i) {{")
                lines.append(f"    {output_name}[i] = {bias_name}[i];")
                lines.append(f"    for (int j = 0; j < {input_size}; ++j) {output_name}[i] += {weight_name}[i * {input_size} + j] * {previous_name}[j];")
                lines.append(f"    {'action[i] = tanh_activation(' + output_name + '[i]);' if is_output else ''}")
                lines.append("  }")
                previous_name = output_name
            elif isinstance(layer, nn.LayerNorm):
                width = layer.normalized_shape[0]
                output_name = f"x{tensor_index}"
                tensor_index += 1
                lines.append(f"  static const float ln_w{index}[{width}] = {{{floats(layer.weight)}}};")
                lines.append(f"  static const float ln_b{index}[{width}] = {{{floats(layer.bias)}}};")
                lines.append(f"  float mean{index} = 0.0f, variance{index} = 0.0f, {output_name}[{width}];")
                lines.append(f"  for (int i = 0; i < {width}; ++i) mean{index} += {previous_name}[i];")
                lines.append(f"  mean{index} /= {width}.0f;")
                lines.append(f"  for (int i = 0; i < {width}; ++i) {{ float d = {previous_name}[i] - mean{index}; variance{index} += d * d; }}")
                lines.append(f"  variance{index} /= {width}.0f;")
                lines.append(f"  for (int i = 0; i < {width}; ++i) {output_name}[i] = ({previous_name}[i] - mean{index}) / std::sqrt(variance{index} + {layer.eps:.9g}f) * ln_w{index}[i] + ln_b{index}[i];")
                previous_name = output_name
            elif isinstance(layer, nn.Tanh):
                lines.append(f"  for (float &value : {previous_name}) value = tanh_activation(value);")
            else:
                raise TypeError(f"Unsupported actor layer for C++ export: {type(layer).__name__}")
        lines.append("}")
        with open(output_path, "w", encoding="utf-8") as header:
            header.write("\n".join(lines) + "\n")
        return output_path

